# constants.py
import pygame

# 화면 설정 (기존 SCREEN_WIDTH -> SIMULATION_AREA_WIDTH로 변경)
SIMULATION_AREA_WIDTH = 800
SIMULATION_AREA_HEIGHT = 600 # 기존 SCREEN_HEIGHT 값 유지

GRAPH_AREA_WIDTH = 300   # 그래프 영역 너비
GRAPH_AREA_X_START = SIMULATION_AREA_WIDTH # 그래프 영역 X 시작 위치

SCREEN_WIDTH = SIMULATION_AREA_WIDTH + GRAPH_AREA_WIDTH # 새 전체 화면 너비
SCREEN_HEIGHT = SIMULATION_AREA_HEIGHT # 전체 화면 높이는 시뮬레이션 영역 높이와 동일

FPS = 360
SIMULATION_TICK_RATE = 0.005

# 기본 색상 정의
BLACK = (0, 0, 0)
WHITE = (255, 255, 255)
GREEN = (0, 255, 0)
BLUE = (0, 0, 255)
RED = (255, 0, 0)
GREY = (200, 200, 200)

# 에너지 풀
INITIAL_GLOBAL_ENERGY_POOL = 30000.0

# 개체 공통
CREATURE_LIFESPAN_TICKS = 800

# 목표 개체 수 비율 및 점유율
TARGET_RATIO_A_SHARE = 0.500
TARGET_RATIO_B_SHARE = 0.309
TARGET_RATIO_C_SHARE = 0.191

# "운(Luck)" 시스템
LUCK_MIN = 0.3
LUCK_MAX = 1.7
LUCK_DEFAULT = 1.0
LUCK_ADJUSTMENT_PERIOD_TICKS = 5
LUCK_ADJUSTMENT_K_FACTOR = 0.8

# 개체 A 설정
CREATURE_A_RADIUS = 5
CREATURE_A_INITIAL_COUNT = 20
CREATURE_A_FIXED_ENERGY = 10.0
CREATURE_A_CREATION_COST = 10.0
CREATURE_A_CREATION_PERIOD_TICKS = 5
CREATURE_A_BASE_CREATION_COUNT = 4

# 개체 B 설정
CREATURE_B_RADIUS = 7
CREATURE_B_INITIAL_COUNT = 12
CREATURE_B_FIXED_ENERGY = 6.18
CREATURE_B_PREY_COUNT_FOR_REPRODUCTION = 3
CREATURE_B_BASE_MOVE_SPEED = 3.0
CREATURE_B_BASE_REPRODUCTION_SUCCESS_RATE = 0.85
CREATURE_B_HUNT_RADIUS = 80

# 개체 C 설정
CREATURE_C_RADIUS = 9
CREATURE_C_INITIAL_COUNT = 7
CREATURE_C_FIXED_ENERGY = 3.82
CREATURE_C_PREY_COUNT_FOR_REPRODUCTION = 2
CREATURE_C_BASE_MOVE_SPEED = 4.0
CREATURE_C_BASE_REPRODUCTION_SUCCESS_RATE = 0.75
CREATURE_C_HUNT_RADIUS = 35

# --- HUD 설정 ---
HUD_AREA_RECT = pygame.Rect(0, 0, SIMULATION_AREA_WIDTH, 50) # HUD 표시 영역
HUD_FONT_SIZE = 24 # HUD 폰트 크기

# --- 그래프 설정 ---
GRAPH_PADDING = 10
GRAPH_MAX_HISTORY = 1000
GRAPH_LINE_THICKNESS = 2
GRAPH_LINE_COLOR_A = (100, 255, 100)
GRAPH_LINE_COLOR_B = (100, 150, 255)
GRAPH_LINE_COLOR_C = (255, 150, 100)
GRAPH_AXIS_COLOR = GREY
GRAPH_BG_COLOR = (20, 20, 20)
GRAPH_TEXT_COLOR = GREY
GRAPH_FONT_SIZE = 18

# --- 시뮬레이션 제어 ---
FAST_FORWARD_FACTORS = [1.0, 2.0, 4.0, 8.0] # 앞으로 감기 속도 배율

# --- 그래프 저장 설정 ---
GRAPH_SAVE_PATH = "simulation_graphs/" # 뒤에 슬래시를 붙여 폴더임을 명시
GRAPH_FILENAME_PREFIX = "population_graph_tick_"
GRAPH_SAVE_DEFAULT_WIDTH = 1200 # 저장될 그래프 이미지의 기본 너비
GRAPH_SAVE_DEFAULT_HEIGHT = 600 # 저장될 그래프 이미지의 기본 높이
GRAPH_SAVE_X_PIXELS_PER_TICK = 1 # 저장 시 틱당 X축 픽셀 수 (0이면 자동 스케일)